import type { Metadata } from "next";
import "./globals.css";
import { Noto_Sans_Bengali } from "next/font/google";
import Providers from "@/components/Providers/Providers";
import { Toaster } from "sonner";

const notoBengali = Noto_Sans_Bengali({
  subsets: ["bengali"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="bn">
      <body
        cz-shortcut-listen="true"
        className={`${notoBengali.className} antialiased no-scrollbar`}
      >
        <Toaster position="top-center" />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
